version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    container_name: server
    ports:
      - 50051:50051
  client:
    build:
      context: .
      dockerfile: Dockerfile_client
    container_name: client