// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: calculate/calculatepb/calculate.proto

package calculatepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Calculation_Method int32

const (
	Calculation_ADD  Calculation_Method = 0
	Calculation_SUB  Calculation_Method = 1
	Calculation_MULT Calculation_Method = 2
	Calculation_DIV  Calculation_Method = 3
	Calculation_SQD  Calculation_Method = 4
	Calculation_ROOT Calculation_Method = 5
)

// Enum value maps for Calculation_Method.
var (
	Calculation_Method_name = map[int32]string{
		0: "ADD",
		1: "SUB",
		2: "MULT",
		3: "DIV",
		4: "SQD",
		5: "ROOT",
	}
	Calculation_Method_value = map[string]int32{
		"ADD":  0,
		"SUB":  1,
		"MULT": 2,
		"DIV":  3,
		"SQD":  4,
		"ROOT": 5,
	}
)

func (x Calculation_Method) Enum() *Calculation_Method {
	p := new(Calculation_Method)
	*p = x
	return p
}

func (x Calculation_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Calculation_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_calculate_calculatepb_calculate_proto_enumTypes[0].Descriptor()
}

func (Calculation_Method) Type() protoreflect.EnumType {
	return &file_calculate_calculatepb_calculate_proto_enumTypes[0]
}

func (x Calculation_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Calculation_Method.Descriptor instead.
func (Calculation_Method) EnumDescriptor() ([]byte, []int) {
	return file_calculate_calculatepb_calculate_proto_rawDescGZIP(), []int{0, 0}
}

type Calculation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A         float64                 `protobuf:"fixed64,1,opt,name=a,proto3" json:"a,omitempty"`
	B         float64                 `protobuf:"fixed64,2,opt,name=b,proto3" json:"b,omitempty"`
	Method    Calculation_Method      `protobuf:"varint,3,opt,name=method,proto3,enum=calculate.Calculation_Method" json:"method,omitempty"`
	Precision *wrapperspb.UInt32Value `protobuf:"bytes,4,opt,name=precision,proto3" json:"precision,omitempty"`
}

func (x *Calculation) Reset() {
	*x = Calculation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculate_calculatepb_calculate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Calculation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calculation) ProtoMessage() {}

func (x *Calculation) ProtoReflect() protoreflect.Message {
	mi := &file_calculate_calculatepb_calculate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calculation.ProtoReflect.Descriptor instead.
func (*Calculation) Descriptor() ([]byte, []int) {
	return file_calculate_calculatepb_calculate_proto_rawDescGZIP(), []int{0}
}

func (x *Calculation) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Calculation) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *Calculation) GetMethod() Calculation_Method {
	if x != nil {
		return x.Method
	}
	return Calculation_ADD
}

func (x *Calculation) GetPrecision() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Precision
	}
	return nil
}

type CalculationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Calc *Calculation `protobuf:"bytes,1,opt,name=calc,proto3" json:"calc,omitempty"`
}

func (x *CalculationRequest) Reset() {
	*x = CalculationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculate_calculatepb_calculate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationRequest) ProtoMessage() {}

func (x *CalculationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculate_calculatepb_calculate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationRequest.ProtoReflect.Descriptor instead.
func (*CalculationRequest) Descriptor() ([]byte, []int) {
	return file_calculate_calculatepb_calculate_proto_rawDescGZIP(), []int{1}
}

func (x *CalculationRequest) GetCalc() *Calculation {
	if x != nil {
		return x.Calc
	}
	return nil
}

type CalculationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result float64 `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CalculationResponse) Reset() {
	*x = CalculationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculate_calculatepb_calculate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationResponse) ProtoMessage() {}

func (x *CalculationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculate_calculatepb_calculate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationResponse.ProtoReflect.Descriptor instead.
func (*CalculationResponse) Descriptor() ([]byte, []int) {
	return file_calculate_calculatepb_calculate_proto_rawDescGZIP(), []int{2}
}

func (x *CalculationResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_calculate_calculatepb_calculate_proto protoreflect.FileDescriptor

var file_calculate_calculatepb_calculate_proto_rawDesc = []byte{
	0x0a, 0x25, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x70, 0x62, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x65, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xde, 0x01, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x61,
	0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x62, 0x12, 0x35,
	0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d,
	0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x3a, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55, 0x49, 0x6e, 0x74, 0x33,
	0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x40, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x44, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x55, 0x42, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x4d, 0x55, 0x4c, 0x54, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x49, 0x56, 0x10, 0x03,
	0x12, 0x07, 0x0a, 0x03, 0x53, 0x51, 0x44, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x4f, 0x4f,
	0x54, 0x10, 0x05, 0x22, 0x40, 0x0a, 0x12, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x63, 0x61, 0x6c,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x04, 0x63, 0x61, 0x6c, 0x63, 0x22, 0x2d, 0x0a, 0x13, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x32, 0x64, 0x0a, 0x12, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0b, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2f,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calculate_calculatepb_calculate_proto_rawDescOnce sync.Once
	file_calculate_calculatepb_calculate_proto_rawDescData = file_calculate_calculatepb_calculate_proto_rawDesc
)

func file_calculate_calculatepb_calculate_proto_rawDescGZIP() []byte {
	file_calculate_calculatepb_calculate_proto_rawDescOnce.Do(func() {
		file_calculate_calculatepb_calculate_proto_rawDescData = protoimpl.X.CompressGZIP(file_calculate_calculatepb_calculate_proto_rawDescData)
	})
	return file_calculate_calculatepb_calculate_proto_rawDescData
}

var file_calculate_calculatepb_calculate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_calculate_calculatepb_calculate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_calculate_calculatepb_calculate_proto_goTypes = []interface{}{
	(Calculation_Method)(0),        // 0: calculate.Calculation.Method
	(*Calculation)(nil),            // 1: calculate.Calculation
	(*CalculationRequest)(nil),     // 2: calculate.CalculationRequest
	(*CalculationResponse)(nil),    // 3: calculate.CalculationResponse
	(*wrapperspb.UInt32Value)(nil), // 4: google.protobuf.UInt32Value
}
var file_calculate_calculatepb_calculate_proto_depIdxs = []int32{
	0, // 0: calculate.Calculation.method:type_name -> calculate.Calculation.Method
	4, // 1: calculate.Calculation.precision:type_name -> google.protobuf.UInt32Value
	1, // 2: calculate.CalculationRequest.calc:type_name -> calculate.Calculation
	2, // 3: calculate.CalculationService.Calculation:input_type -> calculate.CalculationRequest
	3, // 4: calculate.CalculationService.Calculation:output_type -> calculate.CalculationResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_calculate_calculatepb_calculate_proto_init() }
func file_calculate_calculatepb_calculate_proto_init() {
	if File_calculate_calculatepb_calculate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calculate_calculatepb_calculate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Calculation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculate_calculatepb_calculate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculate_calculatepb_calculate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calculate_calculatepb_calculate_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculate_calculatepb_calculate_proto_goTypes,
		DependencyIndexes: file_calculate_calculatepb_calculate_proto_depIdxs,
		EnumInfos:         file_calculate_calculatepb_calculate_proto_enumTypes,
		MessageInfos:      file_calculate_calculatepb_calculate_proto_msgTypes,
	}.Build()
	File_calculate_calculatepb_calculate_proto = out.File
	file_calculate_calculatepb_calculate_proto_rawDesc = nil
	file_calculate_calculatepb_calculate_proto_goTypes = nil
	file_calculate_calculatepb_calculate_proto_depIdxs = nil
}
